
name: Build NanoPi R2S OpenWrt

on:
  schedule:
    - cron: '0 4 * * 5'
  watch:
    types: started

jobs:
  build:
    name: Build OpenWRT
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Init Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo apt-get update
          sudo apt-get -y upgrade
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
          sudo apt-get -y autoremove --purge
          sudo apt-get clean
          
      - name: Get Source Code
        run: |
          git clone https://github.com/coolsnowwolf/lede.git
          cd lede/
          sed -i 's/#src-git helloworld/src-git helloworld/g' feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
      - name: Enable Autocore
        run: |
          cd lede/
          git apply ..config/R2S/All/Autocore.diff
  
      - name: Customization Configuration
        run: |
          cp config/R2S/All/CONFIG_R2S.ini lede/.config
          
      - name: Build OpenWRT
        run: |
          cd lede/
          make defconfig
          make download -j8
          find dl -size -1024c -exec rm -f {} \;
          make -j$(nproc) || make -j1 V=s
          
      - name: Prepare Artifact
        run: find lede/bin/targets/ -type d -name "packages" | xargs rm -rf {}
          
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: Lean.OpenWRT-R2S
          path: lede/bin/targets/*/*/
